version: '3.7'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566-4599:4566-4599'
    environment:
      # All APIs are exposed via a single edge service (default = 4566)
      # JUST PICK WHAT YOU NEED FOR AWS E2E - IF ANYTHING (POSTGRES IS NOT SUPPORTED SO SEPARATE IMAGE USED)
      SERVICES: sqs,lambda,apigateway,iam,sts,s3,cloudformation
      EDGE_PORT: '4566'
      DEBUG: 1
      DEFAULT_REGION: 'eu-west-1'
      AWS_DEFAULT_REGION: 'eu-west-1'
      AWS_ACCESS_KEY: 'foo'
      AWS_SECRET_ACCESS_KEY: 'bar'
      LAMBDA_EXECUTOR: docker
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
