service: sqsl # keep name < 6 chars !!!

frameworkVersion: '2'

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
    host: http://localhost  # optional - LocalStack host to connect to
    edgePort: 4566  # optional - LocalStack edge port to connect to
    debug: true

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
#  lambdaHashingVersion: '20201221'
  stage: local

functions:
  producer:
    handler: handler.producer
    events:
      - http:
          method: post
          path: produce
    environment:
      QUEUE_URL:
        Ref: WorkerQueue

  consumer:
    handler: handler.consumer
    events:
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt:
              - WorkerQueue
              - Arn

resources:
  Resources:
    WorkerQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: workerQueue-${self:provider.stage}
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - WorkerDLQ
              - Arn
          maxReceiveCount: 5
    WorkerDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: workerDlq-${self:provider.stage}
